/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#ffdad6",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "surface-container": "#eaedff",
        "primary-fixed-dim": "#ffb4ab",
        "inverse-on-surface": "#eef0ff",
        "surface-dim": "#d2d9f4",
        "outline": "#906f6b",
        "tertiary-fixed-dim": "#ffb784",
        "background": "#faf8ff",
        "on-secondary-container": "#f9f7ff",
        "tertiary-container": "#ae5800",
        "on-primary-fixed-variant": "#93000d",
        "on-surface": "#131b2e",
        "error": "#ba1a1a",
        "surface-container-high": "#e2e7ff",
        "tertiary": "#8a4400",
        "on-tertiary-fixed-variant": "#713700",
        "surface-bright": "#faf8ff",
        "on-primary-container": "#fff1ef",
        "tertiary-fixed": "#ffdcc6",
        "inverse-surface": "#283044",
        "secondary-fixed-dim": "#b3c5ff",
        "inverse-primary": "#ffb4ab",
        "primary-container": "#d62828",
        "surface": "#faf8ff",
        "on-secondary-fixed-variant": "#003fa4",
        "primary": "#b20112",
        "on-background": "#131b2e",
        "surface-container-highest": "#dae2fd",
        "on-surface-variant": "#5c403d",
        "secondary-fixed": "#dae1ff",
        "surface-variant": "#dae2fd",
        "surface-tint": "#bd1119",
        "on-tertiary-container": "#fff1ea",
        "surface-container-low": "#f2f3ff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#410002",
        "outline-variant": "#e5bdb9",
        "on-tertiary-fixed": "#301400",
        "secondary-container": "#0266ff",
        "secondary": "#0050cc",
        "on-secondary-fixed": "#001849",
        "on-tertiary": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "space-xl": "2.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "margin": "2rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "1rem"
      },
      fontFamily: {
        "label-badge": ["Space Grotesk"],
        "label-md": ["Space Grotesk"],
        "display-hero": ["Space Grotesk"],
        "headline-sm": ["Space Grotesk"],
        "body-sm": ["Lexend"],
        "headline-lg": ["Space Grotesk"],
        "headline-lg-mobile": ["Space Grotesk"],
        "display-hero-mobile": ["Space Grotesk"],
        "body-md": ["Lexend"],
        "headline-md": ["Space Grotesk"],
        "body-lg": ["Lexend"],
        "label-lg": ["Space Grotesk"]
      },
      fontSize: {
        "label-badge": ["11px", { lineHeight: "14px", letterSpacing: "0.1em", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-hero-mobile": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.06em", fontWeight: "700" }]
      }
    }
  },
  plugins: [],
}